# Rename this file to .travis.yml to allow TravisCI integration
sudo: required
language: node_js
node_js:
  - "12.21.0"
dist: xenial

before_deploy:
  - npm run build

stages:
  - stage: test
  - stage: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - npm test

    - stage: deploy
      node_js: lts/*
      env:
        - JOB_NAME="Tag release"
        - GITHUB_URL="https://github.ibm.com"
        - GITHUB_PREFIX="/api/v3"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
          tags: false

#    # Uncomment this section to enable IBM Cloud Object Storage deployments.
#    -
#      env:
#        - JOB_NAME="Deploy to IBM COS"
#        - IBMCLOUD_BUCKET="ibm-widget-boilerplate" # The name of the IBM COS bucket to deploy to
#        - IBMCLOUD_BUCKET_REGION="us-south" # The region that the bucket is deployed in
#      install:
#        - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
#        - ibmcloud plugin install cloud-object-storage
#        - HUSKY_SKIP_INSTALL=1 npm install
#      deploy:
#        provider: script
#        script: "${TRAVIS_BUILD_DIR}/src/core/scripts/travis/deploy-branch ${TRAVIS_BRANCH}"
#        skip_cleanup: true
#        on:
#          branch: master
#          tags: false

#    # Uncomment this section to enable GitHub Pages publishing.
#    -
#      env:
#        - JOB_NAME="Publish GitHub Pages"
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $GITHUB_TOKEN
#        keep_history: true
#        github_url: github.ibm.com
#        local_dir: build
#        verbose: true
#        on:
#          branch: master
#          tags: false