name: Deploy
on:
  push:
    branches:
      - master
jobs:
  Deploy_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Chrome
        run: |
          bash ./.github/scripts/install_chrome.sh
      - name: Install project
        run: npm install
      - name: Run tests
        run: npm test
      - name: Compile production build
        env:
          PUBLIC_URL: ${{ secrets.WEBPACK_PUBLIC_URL }}
        run: NODE_ENV=production npm run build
      - name: Deploy to Akamai NetStorage
        env:
          NETSTORAGE_HOST_NAME: ${{ secrets.NETSTORAGE_HOST_NAME }}
          NETSTORAGE_KEY_NAME: ${{ secrets.NETSTORAGE_KEY_NAME }}
          NETSTORAGE_API_KEY: ${{ secrets.NETSTORAGE_API_KEY }}
          NETSTORAGE_CP_CODE: ${{ secrets.NETSTORAGE_CP_CODE }}
        run: node netstorage.js --sourceDir=build --destinationDir=components
      - name: Publish storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.kyndryl.net/${GITHUB_REPOSITORY}.git
          npx build-storybook
          npx gh-pages -d storybook-static -u "github-actions-bot <support+actions@github.com>"
