name: Publish release
on:
  push:
    branches:
      - 'master'
jobs:
  Publish_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm install
      - name: Publish storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.kyndryl.net/${GITHUB_REPOSITORY}.git
          npm run build:storybook
          npx gh-pages -d storybook-static -u "github-actions-bot <support+actions@github.com>"
      - name: Compile production build
        run: npm run build:prod
      - name: Tag release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: https://github.kyndryl.net
          GITHUB_PREFIX: /api/v3
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.kyndryl.net/${GITHUB_REPOSITORY}.git
          npx semantic-release
